#!/bin/sh
if [ "$OS" = "artixlinux" ] || [ "$OS" = "archlinux" ] || [ "$OS" = "manjaro" ]; then
    pacman -Qqe > "$HOME/extras/pkgs/$HOSTNAME.txt"
elif [ "$OS" = "voidlinux" ]; then
    xpkg -m > "$HOME/extras/pkgs/$HOSTNAME.txt"
fi
