[GLOBAL]
<colon> : command
yy : copy-name
f : fullscreen
G : goto -1
gg : goto 1
m : mark %%
q : quit
. : repeat-command
<shift><down> : scroll down
<shift><left> : scroll left
<shift><right> : scroll right
<shift><up> : scroll up
/ : search
? : search --reverse
N : search-next
P : search-prev
b : set statusbar.show!
tl : toggle library
tm : toggle manipulate
tt : toggle thumbnail

[IMAGE]
| : flip
_ : flip --vertical
<end> : goto -1
<home> : goto 1
<right> : next
<left> : prev
<space> : play-or-pause
> : rotate
< : rotate --counter-clockwise
<equal> : scale --level=fit
+ : zoom in
- : zoom out

[LIBRARY]
go : goto 1 --open-selected
n : scroll down --open-selected
p : scroll up --open-selected

[THUMBNAIL]
+ : zoom in
- : zoom out

[COMMAND]
<tab> : complete
<shift><tab> : complete --inverse
<up> : history-substr-search next
<down> : history-substr-search prev
<escape> : leave-commandline

[MANIPULATE]
<colon> : command
f : fullscreen
b : set statusbar.show!

