#!/usr/bin/env sh
# shellcheck disable=3028
set -ex

xbps-install -Su
xbps-install -S void-repo-nonfree
xbps-install -S $(cat "etc/pkgs/$HOSTNAME.txt")

sed -i 's/^#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/g;s/^#pt_BR.UTF-8 UTF-8/pt_BR.UTF-8 UTF-8/g' /etc/default/libc-locales
xbps-reconfigure -f glibc-locales
cp -f etc/locale.conf /etc/locale.conf
cp -f etc/voidlinux/default/grub /etc/default/grub

chsh -s /bin/fish root
chsh -s /bin/sh lucas

cp etc/voidlinux/ignore-sudo.conf /etc/xbps.d/
xbps-remove -R sudo
cp etc/doas.conf /etc/

ln -s /etc/sv/socklog-unix /var/service/
ln -s /etc/sv/nanoklogd /var/service/

cp etc/voidlinux/rc.local /etc/rc.local

ln -s /etc/sv/acpid /var/service/
ln -s /etc/sv/tlp /var/service/

[ "$(wc -l /etc/hosts)" -lt 15 ] && cat etc/hosts >>/etc/hosts

ln -s /etc/sv/dbus /var/service/

[ -e "/etc/sv/turnstiled" ] &&
	ln -s /etc/sv/turnstiled /var/service/

[ -e "/etc/sv/seatd" ] &&
	ln -s /etc/sv/seatd /var/service/ &&
	usermod -aG _seatd lucas

xbps-install -S linux-firmware-amd mesa-dri vulkan-loader mesa-vulkan-radeon amdvlk xf86-video-amdgpu xf86-video-ati mesa-vaapi mesa-vdpau

mkdir -p /etc/pipewire/pipewire.conf.d
ln -s /usr/share/examples/wireplumber/10-wireplumber.conf /etc/pipewire/pipewire.conf.d/
ln -s /usr/share/examples/pipewire/20-pipewire-pulse.conf /etc/pipewire/pipewire.conf.d/

mkdir -p /etc/alsa/conf.d
ln -s /usr/share/alsa/alsa.conf.d/50-pipewire.conf /etc/alsa/conf.d
ln -s /usr/share/alsa/alsa.conf.d/99-pipewire-default.conf /etc/alsa/conf.d

usermod -aG audio lucas
usermod -aG video lucas

echo "/usr/lib/pipewire-0.3/jack" > /etc/ld.so.conf.d/pipewire-jack.conf
ldconfig

mkdir -p /etc/X11
cp -r etc/X11/xorg.conf.d/ /etc/X11/

cat etc/pam.d/login >>/etc/pam.d/login

cat etc/containers/registries.conf >>/etc/containers/registries.conf

ln -s /etc/sv/bluetoothd /var/service/
usermod -aG bluetooth lucas

chown -R lucas:lucas /home/lucas/.local/bin

/usr/share/qutebrowser/scripts/dictcli.py install en-US
/usr/share/qutebrowser/scripts/dictcli.py install pt-BR

# fix some udev errors on t14
mkdir -p /etc/udev/hwdb.d/
cp  etc/60-keyboard.hwdb /etc/udev/hwdb.d/
udevadm hwdb --update && udevadm control --reload-rules && udevadm trigger

cat etc/voidlinux/security/limits.conf >>/etc/security/limits.conf
usermod -aG input lucas
