#!/usr/bin/env sh
# shellcheck disable=3028
set -ex

xbps-install -Su
xbps-install -S void-repo-nonfree
xbps-install -S $(cat "etc/pkgs/$HOSTNAME.txt")

sed -i 's/^#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/g;s/^#pt_BR.UTF-8 UTF-8/pt_BR.UTF-8 UTF-8/g' /etc/default/libc-locales
xbps-reconfigure -f glibc-locales
cp -f etc/locale.conf /etc/locale.conf
cp -f etc/voidlinux/default/grub /etc/default/grub

chsh -s /bin/fish root
chsh -s /bin/sh lucas

cp etc/voidlinux/ignore-sudo.conf /etc/xbps.d/
xbps-remove -R sudo
cp etc/doas.conf /etc/

ln -s /etc/sv/socklog-unix /var/service/
ln -s /etc/sv/nanoklogd /var/service/

cp etc/voidlinux/rc.local /etc/rc.local

ln -s /etc/sv/acpid /var/service/

[ "$(wc -l /etc/hosts)" -lt 15 ] && cat etc/hosts >>/etc/hosts

ln -s /etc/sv/dbus /var/service/

[ -e "/etc/sv/seatd" ] &&
	ln -s /etc/sv/seatd /var/service/ &&
	usermod -aG _seatd lucas

xbps-install -S linux-firmware-amd mesa-dri vulkan-loader amdvlk mesa-vdpau mesa-vaapi

mkdir -p /etc/alsa/conf.d
ln -s /usr/share/alsa/alsa.conf.d/50-pipewire.conf /etc/alsa/conf.d
ln -s /usr/share/alsa/alsa.conf.d/99-pipewire-default.conf /etc/alsa/conf.d
xbps-reconfigure -f alsa-pipewire

echo "/usr/lib/pipewire-0.3/jack" > /etc/ld.so.conf.d/pipewire-jack.conf
ldconfig

mkdir -p /etc/X11
cp -r etc/X11/xorg.conf.d/ /etc/X11/

cat etc/pam.d/login >>/etc/pam.d/login

mkdir -p /home/lucas/.local/bin/
(
	cd code/c/st/
	./build.sh
)

(
	cd code/c/gf/
	./build.sh
	cp ./gf2 /home/lucas/.local/bin/
)

(
	cd code/c/ueberzugpp/
	mkdir build && cd build
	cmake -DCMAKE_BUILD_TYPE=Release ..
	cmake --build .
	cp ./ueberzug ./ueberzugpp /home/lucas/.local/bin/
)

npm i -g cssmodules-language-server @tailwindcss/language-server typescript \
	typescript-language-server vscode-langservers-extracted \
	fixjson bash-language-server vscode-css-languageserver-bin \
	neovim write-good quick-lint-js stylelint

cp etc/containers/ /etc/

ln -s /etc/sv/bluetoothd /var/service/
usermod -aG bluetooth lucas

chown -R lucas:lucas /home/lucas/.local/bin

/usr/share/qutebrowser/scripts/dictcli.py install en-US
/usr/share/qutebrowser/scripts/dictcli.py install pt-BR
