#!/usr/bin/env sh
set -ex

export HOSTNAME="$(uname -n)"
export home="$HOME"
export user="$USER"

[ "$(pwd)" != "$HOME" ] && echo "Not in your home folder!" && exit 1

if [ -d etc/.dotfiles ]; then
	su -c 'xbps-install -S git'
	
	# git was a mistake
	GIT_FLAGS="--work-tree=. --git-dir=etc/.dotfiles/"

	git clone --bare https://codeberg.org/lucastavaresa/dotfiles etc/.dotfiles
	git $GIT_FLAGS restore -WS .
	git $GIT_FLAGS submodule update --init --recursive
	git $GIT_FLAGS config --local --add remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*'
	git $GIT_FLAGS fetch
	git $GIT_FLAGS branch --set-upstream-to=origin/main main
fi

su -c "$HOME/etc/voidlinux/voidinstallroot"

export CARGO_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/cargo"
mkdir -p "$home/.local/share/cargo/"
cargo install --locked yazi-fm handlr-regex tree-sitter-cli bluetui

export GOPATH="${XDG_DATA_HOME:-$HOME/.local/share}/go"
mkdir -p "$home/.local/share/go/"
go install github.com/nao1215/gup@latest
go install github.com/segmentio/golines@latest
go install github.com/cespare/reflex@latest
go install github.com/EwenQuim/entropy@latest

pipx install scdl
pipx install spotdl
pipx install pyright

mkdir -p "$home/.local/share/applications/"
cp etc/transmission-remote.desktop "$home/.local/share/applications/"
cp etc/term_open.desktop "$home/.local/share/applications/"
cp etc/yazi.desktop "$home/.local/share/applications/"

mkdir -p "$home/.mozilla/firefox/myprofile/chrome/"
cp etc/userChrome.css "$home/.mozilla/firefox/myprofile/chrome/"

mkdir -p "$home/.local/share/wget"
touch "$home/.local/share/wget/wgetrc"

npm i -g typescript typescript-language-server vscode-langservers-extracted \
	bash-language-server vscode-css-languageserver-bin neovim quick-lint-js stylelint

(
	cd code/c/gf/
	doas xbps-install -S libX11-devel freetype-devel
	./build.sh
	cp ./gf2 /home/lucas/.local/bin/
	doas xbps-remove -R libX11-devel freetype-devel
)

(
	cd code/c/ueberzugpp/
	mkdir -p build && cd build
	doas xbps-install -S tbb-devel libopencv-devel libwebp-devel pango-devel librsvg-devel libopenexr-devel orc-devel poppler-glib-devel chafa-devel xcb-util-image-devel libvips-devel libsixel-devel
	cmake -DCMAKE_BUILD_TYPE=Release ..
	cmake --build .
	cp ./ueberzug ./ueberzugpp /home/lucas/.local/bin/
	doas xbps-remove -R tbb-devel libopencv-devel libwebp-devel pango-devel librsvg-devel libopenexr-devel orc-devel poppler-glib-devel chafa-devel xcb-util-image-devel libvips-devel libsixel-devel
)
