# bashrc trocado de lugar colocando ". local/do/bashrc" no final de "/etc/bash.bashrc"

# se não executando bash interativamente
# não executa o resto do bashrc
[[ $- != *i* ]] && return

#### Bash exports ####
export SHELL="bash"
export GIT_TTY=$(tty)

#### Aliases ####
alias as="alias | grep --color -i"
alias n="neofetch"
alias v="nvim"
alias vv="st -e nvim"
alias h="htop"
alias ed="emacs --daemon"
alias ek="emacsclient -e '(kill-emacs)'"
alias ec="emacsclient -n -c"
alias e="emacs"
alias copy="xclip -selection clipboard"
alias sudo="doas"
alias ping="ping google.com"
alias p="patch -p1 <"
alias pr="patch -R <"
alias yt="yt-dlp"
alias yta="yt-dlp -x --audio-format mp3"
alias ka="killall"
alias mi="make install"
alias mu="make uninstall"
alias dh="doom help"
alias ds="doom sync"
alias dd="doom doctor"
alias du="doom upgrade"
alias dr="doom_reset"
alias dp="doom purge"
alias dmi="doas make install"
alias dmu="doas make uninstall"
alias dnr="dotnet run"
alias dnn="dotnet new"
alias dns="dotnet-script"
alias xp="xprop"
alias xk="xkill"
alias grep="grep --color -i -I"
alias sys="doas systemctl"
# arquivos e Diretórios
alias l="lsd -lXA1 --group-dirs first"
alias la="lsd -AX1 --group-dirs first"
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias lo="locate -Ai"
alias u="doas updatedb"
alias ch="chmod +x"
alias cp="cp -ri"
alias mv="mv -i"
alias rm="rm -rI"
alias rmf="rm -rf"
alias ln="ln -i"
alias md="mkdir -p"
alias t="touch"
alias mnt="doas mount"
alias umnt="doas umount"
# git
alias gi="git init"
alias gc="git clone"
alias gs="git status"
alias gsr="git_status_recursivo"
alias gpr="find . -mindepth 2 -maxdepth 2 | xargs -I{} git -C {} pull"
alias gd="git diff"
alias gds="git diff --staged"
alias gl="git log --oneline"
alias ga="git add"
alias gaf="git add -f"
alias gcm="git commit"
alias gcmm="git commit -m"
alias gco="git checkout"
alias gps="git push"
alias gpsf="git push -f"
alias gpl="git pull"
alias gf="git fetch"
alias gr="git restore"
alias grs="git restore --staged"
alias grrs="git reset --soft"
alias grrh="git reset --hard"

## aliases em systemas
if [ "$OS" = "voidlinux" ]; then
    # xbps
    alias xis="doas xbps-install -S"
    alias xqr="xbps-query -R"
    alias xqrs="xbps-query -Rs"
    alias xisu="doas xbps-install -Su"
    alias xql="xbps-query -l"
    alias xrr="doas xbps-remove -R"
    alias xqp="xbps-query -p install-date -s '' | sort -k2 | column -t"
elif [ "$OS" = "archlinux" ] || [ "$OS" = "manjaro" ]; then
    # pacman
    alias ps="doas pacman -S"
    alias psi="pacman -Si"
    alias pss="pacman -Ss"
    alias psyu="doas pacman -Syu"
    alias pq="pacman -Q"
    alias pqs="pacman -Qs"
    alias prns="doas pacman -Rns"
    alias exp="expac --timefmt='%Y-%m-%d %T' '%l\t%n' | sort | tail -n"
    # paru
    alias pps="paru -S"
    alias ppsi="paru -Si"
    alias ppss="paru -Ss"
    alias ppsyu="paru -Syu"
    alias ppq="paru -Q"
    alias ppqs="paru -Qs"
    alias pprns="paru -Rns"
elif [ "$OS" = "linuxmint" ]; then
    alias bat="batcat"
    # apt
    alias ai="doas apt install"
    alias as="apt show"
    alias ass="apt search"
    alias auau="doas apt update && doas apt upgrade"
    alias ali="apt list --installed"
    alias ar="doas apt remove"
fi

# ignora case-sensitivity quando completa comandos com tab
if [ ! -a $HOME/.config/readline/inputrc ]; then echo '$include /etc/inputrc' > $HOME/.config/readline/inputrc; fi
echo 'set completion-ignore-case On' >> $HOME/.config/readline/inputrc
# corrige automaticamente erros ao usar o cd
shopt -s cdspell
# salva comandos de múltiplas linhas como uma linha única
shopt -s cmdhist

#### Funções ####
# hersbstluftwm
hc () {
    herbstclient "$@"
}

# previsão de imagens no lf
lf () {
    LF_TEMPDIR="$(mktemp -d -t lf-tempdir-XXXXXX)"
    LF_TEMPDIR="$LF_TEMPDIR" lf-run -last-dir-path="$LF_TEMPDIR/lastdir" "$@"
    if [ "$(cat "$LF_TEMPDIR/cdtolastdir" 2>/dev/null)" = "1" ]; then
    cd "$(cat "$LF_TEMPDIR/lastdir")"
    fi
    rm -r "$LF_TEMPDIR"
    unset LF_TEMPDIR
}

# facilita extrair arquivos
# exemplo: ex <arquivo>
ex () {
  if [ -f "$1" ] ; then
    case $1 in
      *.tar.bz2)   tar xjf $1   ;;
      *.tar.gz)    tar xzf $1   ;;
      *.bz2)       bunzip2 $1   ;;
      *.rar)       unrar x $1   ;;
      *.gz)        gunzip $1    ;;
      *.tar)       tar xf $1    ;;
      *.tbz2)      tar xjf $1   ;;
      *.tgz)       tar xzf $1   ;;
      *.zip)       unzip $1     ;;
      *.Z)         uncompress $1;;
      *.7z)        7z x $1      ;;
      *.deb)       ar x $1      ;;
      *.tar.xz)    tar xf $1    ;;
      *.tar.zst)   unzstd $1    ;;
      *)           echo "'$1' não pode ser extraído com ex()" ;;
    esac
  else
    echo "'$1' não é um arquivo valido"
  fi
}

# localizar e editar arquivo
vw () {
    nvim $(where $1)
}

# prompt
PS1="\e[01;37m[\u@\h] \w\e[m \e[01;32m>\e[m"
