#!/usr/bin/env bash

pegar_erros() {
    trap '' ERR
    local frame=0 str
    local stacktrace="Comando fechado com status $1\n\nStack:"
    while str=$(caller $frame); do
        stacktrace+="\nlinha $str"
        frame=$((frame+1))
    done
    notify-send -u critical "Erro de configuração no hlwm" "$stacktrace"
}
set -o errtrace
trap 'pegar_erros $?' ERR

hc() {
    herbstclient "$@"
}

primeira_vez_aberto() {
    ! hc silent get_attr my_loaded 2>/dev/null
}

hc emit_hook reload

# remove todas as teclas de atalho
hc keyunbind --all
hc mouseunbind --all

# atalhos do mouse
hc mousebind Super-Button1 move
hc mousebind Super-Button2 zoom
hc mousebind Super-Button3 resize

# adiciona tags no primeiro iniciar
if primeira_vez_aberto; then
    tag_names=( {1..4} )
    hc rename default "${tag_names[0]}" || true
    for i in "${!tag_names[@]}"; do
        hc add "${tag_names[$i]}"
    done
    hc detect_monitors
fi
tag_keys=( {1..4} 0 )
tag_count=$(hc attr tags.count)
for i in "${!tag_keys[@]}"; do
    (( i >= tag_count )) && break
    key="${tag_keys[$i]}"
done

hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc attr theme.active.color '#ffffff'
hc attr theme.normal.color '#000000'
hc attr theme.urgent.color '#ff0000'
hc attr theme.inner_color '#000000'
hc attr theme.floating.outer_color '#000000'
hc attr theme.active.inner_color '#ffffff'
hc attr theme.active.outer_color '#ffffff'
hc attr theme.background_color '#000000'
hc attr theme.inner_width 0
hc attr theme.border_width 1
hc attr theme.floating.border_width 1
hc attr theme.floating.outer_width 0

hc set frame_border_active_color '#ffffff'
hc set frame_border_normal_color '#000000'
hc set frame_bg_active_color '#111111'
hc set frame_bg_normal_color '#000000'
hc set auto_detect_panels false
hc set default_frame_layout max
hc set always_show_frame 0
hc set frame_border_width 1
hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set frame_padding 0
hc set frame_gap 0
hc set smart_frame_surroundings 1
hc set smart_window_surroundings 1
hc set window_gap 0
hc set focus_follows_mouse 0
hc set raise_on_focus 1
hc set mouse_recenter_gap 0
hc set swap_monitors_to_get_tag 1
hc set tree_style '╾│ ├└╼─┐'

#### Regras ####
hc unrule -F
hc rule focus=on # focar novas janelas
hc rule floatplacement=smart
# programas
hc rule class="qutebrowser" tag=1
hc rule class="firefox" tag=1
hc rule class="Emacs" tag=2
hc rule class="nvim" tag=2
hc rule class="st-256color" tag=2
hc rule class="mpv" tag=3
hc rule class="Gimp" tag=3
hc rule class="Xephyr" tag=3
hc rule class="discord" tag=4
hc rule class="TelegramDesktop" tag=4
# flutuantes
hc rule class="ncmpcpp" floating=on floatplacement=center
hc rule class="pulsemixer" floating=on floatplacement=center
hc rule class="MEGAsync" floating=on floatplacement=center
hc rule class="Transmission-gtk" floating=on floatplacement=center
hc rule class="Galculator" floating=on floatplacement=center
hc rule class="htop" floating=on floatplacement=center
# notificações, pop-ups, etc.
hc rule class="qutebrowser" windowtype='_NET_WM_WINDOW_TYPE_UTILITY' floating=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on floatplacement=center
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule class="Pinentry-gtk-2" floating=on floatplacement=center

polybar &
# espera a barra carregar e esconde a barra
sleep 5 && polybar-msg cmd hide
hc unlock
