#!/usr/bin/env bash

hc() {
    herbstclient "$@"
}

hc emit_hook reload

pegar_erros() {
    trap '' ERR
    local frame=0 str
    local stacktrace="Comando fechado com status $1\n\nStack:"
    while str=$(caller $frame); do
        stacktrace+="\nlinha $str"
        frame=$((frame+1))
    done
    notify-send -u critical "Erro de configuração no hlwm" "$stacktrace"
}
set -o errtrace
trap 'pegar_erros $?' ERR

primeira_vez_aberto() {
    ! hc silent get_attr my_loaded 2>/dev/null
}

############
#  Teclas  #
############
# remove todas as teclas de atalho
hc keyunbind --all
hc mouseunbind --all

# atalhos do mouse
hc mousebind Super-Button1 move
hc mousebind Super-Button2 zoom
hc mousebind Super-Button3 resize

# adiciona tags no primeiro iniciar
if primeira_vez_aberto; then
    hc set default_frame_layout max
    hc set_layout max
    tag_names=( {1..4} )
    hc rename default "${tag_names[0]}" || true
    for i in "${!tag_names[@]}"; do
        hc add "${tag_names[$i]}"
    done
    hc detect_monitors
fi
tag_keys=( {1..4} 0 )
tag_count=$(hc attr tags.count)
for i in "${!tag_keys[@]}"; do
    (( i >= tag_count )) && break
    key="${tag_keys[$i]}"
    hc keybind "Mod4-$key" use_index "$i"
    hc keybind "Mod4-Shift-$key" move_index "$i"
done

# Herbstluftwm
hc keybind Mod4-q close
hc keybind Mod4-Shift-q remove
hc keybind Mod4-f spawn hlwm_control estado telacheia
hc keybind Mod4-w spawn hlwm_control estado flutuante
hc keybind Mod4-Tab cycle_all +1
hc keybind Mod4-Alt-period cycle_all +1
# troca entre layouts pulando layouts que não mudam janelas de posição
hc keybind Mod4-Escape or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1
hc keybind Mod4-Alt-comma or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1
# Direcionais
# troca foco de janela e tag
hc keybind Mod4-Up focus up
hc keybind Mod4-Down focus down
hc keybind Mod4-Left or . focus left . use_index -1
hc keybind Mod4-Right or . focus right . use_index +1
# troca posição da janela
hc keybind Mod4-Shift-Up shift up
hc keybind Mod4-Shift-Down shift down
hc keybind Mod4-Shift-Left shift left
hc keybind Mod4-Shift-Right shift right
# troca janela de tag e a segue
hc keybind Mod4-Alt-Left and . move_index -1 . use_index -1
hc keybind Mod4-Alt-Right and . move_index +1 . use_index +1
# cria divisória
hc keybind Mod4-Ctrl-Shift-Up split top
hc keybind Mod4-Ctrl-Shift-Down split bottom
hc keybind Mod4-Ctrl-Shift-Left split left
hc keybind Mod4-Ctrl-Shift-Right split right
# muda o tamanho da divisória
hc keybind Mod4-Ctrl-Up resize up +0.05
hc keybind Mod4-Ctrl-Down resize down +0.05
hc keybind Mod4-Ctrl-Left resize left +0.05
hc keybind Mod4-Ctrl-Right resize right +0.05
# Vimkeys
# troca foco de janela e tag
hc keybind Mod4-k focus up
hc keybind Mod4-j focus down
hc keybind Mod4-h or . focus left . use_index -1
hc keybind Mod4-l or . focus right . use_index +1
# troca posição da janela
hc keybind Mod4-Shift-k shift up
hc keybind Mod4-Shift-j shift down
hc keybind Mod4-Shift-h shift left
hc keybind Mod4-Shift-l shift right
# troca janela de tag e a segue
hc keybind Mod4-Alt-h and . move_index -1 . use_index -1
hc keybind Mod4-Alt-l and . move_index +1 . use_index +1
# cria divisória
hc keybind Mod4-Ctrl-Shift-k split top
hc keybind Mod4-Ctrl-Shift-j split bottom
hc keybind Mod4-Ctrl-Shift-h split left
hc keybind Mod4-Ctrl-Shift-l split right
# muda o tamanho da divisória
hc keybind Mod4-Ctrl-k resize up +0.05
hc keybind Mod4-Ctrl-j resize down +0.05
hc keybind Mod4-Ctrl-h resize left +0.05
hc keybind Mod4-Ctrl-l resize right +0.05
# Aplicações
hc keybind Mod4-Shift-Return spawn st
hc keybind Mod4-backslash spawn st_scratchpad
hc keybind Alt-h spawn st -c htop -n htop -e htop
hc keybind Alt-Shift-p spawn hlwm_control picom
hc keybind Alt-f spawn sct
hc keybind Alt-Shift-f spawn sct 2000
hc keybind Alt-t spawn transmission-qt
hc keybind Alt-a spawn $VISUAL ~/documentos/anotações.md
# Musica
hc keybind Mod4-a spawn st -c ncmpcpp -n ncmpcpp -e ncmpcpp
hc keybind Mod4-Shift-a spawn st -c pulsemixer -n pulsemixer -e pulsemixer
hc keybind Mod4-space or . spawn playerctl play-pause . spawn mpc toggle
hc keybind Mod4-comma spawn amixer -q set Master 5%-
hc keybind Mod4-period spawn amixer -q set Master 5%+
hc keybind Mod4-Shift-comma and . spawn mpc prev . spawn musica notificar
hc keybind Mod4-Shift-period and . spawn mpc next . spawn musica notificar
# Menus
hc keybind Menu spawn dmenu_run info
hc keybind Mod4-s spawn dmenu_sys
hc keybind Alt-q spawn dmenu_qutebrowser ~/code/shell/listas/favoritos.yaml
hc keybind Alt-e spawn dmenu_edit
hc keybind Alt-w spawn dmenu_wifi
hc keybind Alt-x spawn dmenu_xephyr
hc keybind Mod4-c spawn st -c fzf -n fzf -e fzf_clip
hc keybind Alt-p spawn passmenu --type
hc keybind Alt-m spawn st -e fzf_man
hc keybind Alt-Shift-m spawn dmenu_mont
hc keybind Alt-Shift-e spawn st -c fzf -n fzf fzf_emojis
hc keybind Print spawn dmenu_print

hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc attr theme.active.color '#ffffff'
hc attr theme.normal.color '#000000'
hc attr theme.urgent.color '#ff0000'
hc attr theme.inner_color '#000000'
hc attr theme.active.inner_color '#ffffff'
hc attr theme.active.outer_color '#ffffff'
hc attr theme.background_color '#000000'
hc attr theme.inner_width 0
hc attr theme.border_width 1
hc attr theme.floating.border_width 4
hc attr theme.floating.inner_width 2
hc attr theme.floating.outer_width 2
hc attr theme.floating.outer_color '#000000'
hc attr theme.floating.inner_color '#000000'
hc attr theme.floating.active.inner_color '#ffffff'
hc attr theme.floating.active.outer_color '#000000'

hc set frame_border_active_color '#ffffff'
hc set frame_border_normal_color '#000000'
hc set frame_bg_active_color '#111111'
hc set frame_bg_normal_color '#000000'
hc set auto_detect_panels false
hc set tabbed_max 1
hc set always_show_frame 0
hc set frame_border_width 1
hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set frame_padding 0
hc set frame_gap 0
hc set smart_frame_surroundings 1
hc set smart_window_surroundings 1
hc set window_gap 0
hc set focus_follows_mouse 0
hc set raise_on_focus 1
hc set mouse_recenter_gap 0
hc set swap_monitors_to_get_tag 1
hc set tree_style '╾│ ├└╼─┐'
hc set snap_gap 0

#### Regras ####
hc unrule -F
hc rule focus=on # focar novas janelas
hc rule floatplacement=center
# programas
hc rule class="qutebrowser" tag=1 switchtag=on
hc rule class="firefox" tag=1 switchtag=on
hc rule class="Emacs" tag=2 switchtag=on
hc rule class="nvim" tag=2 switchtag=on
hc rule class="st-256color" tag=2 switchtag=on
hc rule class="mpv" tag=3 switchtag=on
hc rule class="Gimp" tag=3 switchtag=on
hc rule class="Xephyr" tag=3 switchtag=on
hc rule class="discord" tag=4 switchtag=on
hc rule class="TelegramDesktop" tag=4 switchtag=on
# flutuantes
hc rule class="fzf" floating=on floatplacement=center
hc rule class="ncmpcpp" floating=on floatplacement=center
hc rule class="pulsemixer" floating=on floatplacement=center
hc rule class="MEGAsync" floating=on floatplacement=center
hc rule class="transmission" floating=on floatplacement=center
hc rule class="Galculator" floating=on floatplacement=center
hc rule class="htop" floating=on floatplacement=center
hc rule class="GParted" floating=on floatplacement=center
hc rule class="Nitrogen" floating=on floatplacement=center
hc rule class="pinentry-qt" floating=on floatplacement=center
# notificações, pop-ups, etc.
hc rule class="qutebrowser" windowtype='_NET_WM_WINDOW_TYPE_UTILITY' floating=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on floatplacement=center
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# polybar
# polybar pc &
# espera a barra carregar e esconde a barra
# sleep 5 && polybar-msg cmd hide

# troca capslock por escape
setxkbmap -option caps:escape # grep -E "(ctrl|caps):" /usr/share/X11/xkb/rules/base.lst
xset r rate 300 100 # acelera repetição de teclas

if [ "$HOSTNAME" = *"note"* ]; then
    # teclas no notebook
    # alt + , = Escape
    xmodmap -e "keycode 59 = comma less comma less Escape"
    # alt + . = Tab
    xmodmap -e "keycode 60 = period greater period greater Tab"
    # alt + ; = "
    xmodmap -e "keycode 61 = semicolon colon semicolon colon quotedbl"
fi

hc unlock
