#!/usr/bin/env sh

# miscelânea
# xautolock -detectsleep -time 30 -locker "slock" -notify 30 -notifier "notify-send Slock -u critical -t 1800000 'BLOQUEANDO A TELA 30 SEGUNDOS'" &
mkdir .cache/clipmenu
export CM_DIR="$HOME/.cache/clipmenu"
pgrep -i -f clipmenu || clipmenud &
pgrep -i -f dunst || dunst &
pgrep -i -f xbanish || xbanish &
pgrep -i -f syncthing || syncthing &
pgrep -i -f emacs || doom_reset &
pgrep -i -f barrier || barrier &
fzf_man update &
# musica
pgrep -i -f playerctld || playerctld daemon &
pgrep -i -f mpd || mpd &
pgrep -i -f mpDris2 || mpDris2 --music-dir="$HOME/media/musicas/" &
mpc update &
# aparencia
pgrep -i -f picom || picom &
nitrogen --restore &
xsetroot -cursor_name left_ptr
xrdb -load "$HOME/.config/x11/xresources" &
# sistema
checar_updates &

if [ "$WM" = "herbstluftwm" ]; then
    flags=" --locked"
elif [ "$WM" = "dwm" ]; then
    sxhkd -c "$HOME/.config/sxhkd/sxhkd_dwm" &
    dwmblocks &
elif [ "$WM" = "ratpoison" ]; then
    flags=" -f $HOME/.config/ratpoison/config"
elif [ "$WM" = "bspwm" ]; then
    sxhkd -c "$HOME/.config/sxhkd/sxhkd_bspwm" &
else
    sxhkd -c "$HOME/.config/sxhkd/sxhkd_nowm" &
fi

if [ -n "$flags" ]; then
    ssh-agent $WM$flags
else
    ssh-agent "$WM"
fi
