#!/bin/sh

# Mouse
xsetroot -cursor_name left_ptr

# Teclado
setxkbmap -option caps:escape # muda a função da tecla caps lock para esc
xset r rate 300 100 # acelera repetição de teclas

# Gnome keyring daemon
eval "$(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)"
export SSH_AUTH_SOCK
. /etc/X11/xinit/xinitrc.d/50-systemd-user.sh

# Clipmenu
systemctl --user import-environment DISPLAY
export CM_DIR="$HOME/code/dmenuscripts/listas/clipmenu"
clipmenud &

# Outros
mpd &
nm-applet &
dunst &
nitrogen --restore &
xbanish &
fluxgui &
slstatus &
sxhkd &
emacs --daemon &

# Protetor de tela
xautolock -detectsleep -time 30 -locker "slock" -notify 30 -notifier "notify-send Slock -u critical -t 1800000 'BLOQUEANDO A TELA 30 SEGUNDOS'" &

exec dwm
