#!/usr/bin/env sh
# miscelânea
xautolock -detectsleep -time 30 -locker "slock" -notify 30 -notifier "notify-send Slock -u critical -t 1800000 'BLOQUEANDO A TELA 30 SEGUNDOS'" &
mkdir .cache/clipmenu
export CM_DIR="$HOME/.cache/clipmenu"
clipmenud &
dunst &
xbanish &

# musica
pgrep -x "mpDris2" || mpDris2 --music-dir="$HOME/media/musicas/" >"$XDG_CACHE_HOME/mpdris2.log" 2>&1 &
pgrep -x "playerctld" || playerctld daemon

# aparência
[ "$HOSTNAME" = "$OS"pc ] && xrandr --output VGA-1 --mode 1280x720 --rate 75.02
[ "$HOSTNAME" = "$OS"note ] && xrandr --output LVDS --set TearFree on
picom &
nitrogen --restore
xsetroot -cursor_name left_ptr
xrdb -load "$HOME/.config/x11/xresources"

# teclado
# acelera repetição de teclas
xset r rate 300 100
setxkbmap -layout us -option caps:swapescape # grep escape /usr/share/X11/xkb/rules/base.lst

# sistema
checar_updates &

if [ "$WM" = "herbstluftwm" ]; then
	args="--locked"
fi

if [ -n "$args" ]; then
	eval ssh-agent "$WM $args"
else
	ssh-agent "$WM"
fi
