#!/usr/bin/env sh
## Miscellanea ##
fzf_man update &
pgrep -i -f emacs || doom_reset &
pgrep -i -f foot || foot --server &
pgrep -i -f dunst || dunst &
pgrep -i -f syncthing || syncthing &
pgrep -i -f clipman || wl-paste -t text --watch clipman store &
## Musica ##
pgrep -i -f mpd || mpd &
pgrep -i -f mpd || mpc update &
## Aparência ##
pgrep -i -f wbg || wbg "$HOME/media/imagens/wallpapers/E4BFdWlVIAEi8S.jpg" &
## Sistema ##
checar_updates &
########################
# xrdb -load "$HOME/.config/x11/xresources" &
# pgrep playerctld || playerctld daemon &
# pgrep mpDris2 || mpDris2 --music-dir="$HOME/media/musicas/" &
# pgrep barrier || barrier &
# xautolock -detectsleep -time 30 -locker "slock" -notify 30 -notifier "notify-send Slock -u critical -t 1800000 'BLOQUEANDO A TELA 30 SEGUNDOS'" &
exec <&-
