#!/usr/bin/env sh
set -ex

eprintf() {
	# shellcheck disable=SC2059 # format string is provided by the caller
	printf "$@" >&2
	exit 1
}

has() {
	_cmd=$(command -v "$1" 2>/dev/null) || return 1
	[ -x "$_cmd" ] || return 1
}

printf "Enter username (default: '%s'): " "$LOGNAME"
read -r user
[ -n "$user" ] || user="$LOGNAME"

home="/home/$user"
[ -d "$home" ] || eprintf "'%s' does not exist!" "$home"
[ "$(pwd)" != "$home" ] && eprintf "You need to be in your home directory!"
has git || eprintf "You need git to run this install script!"

git_dir="$home/etc/.dotfiles"

dotgit() {
	git --work-tree=. --git-dir="$git_dir" "$@"
}

if [ "$(dotgit rev-parse --is-bare-repository 2>/dev/null)" != "true" ]; then
	if [ -e "$git_dir" ]; then
		eprintf "'%s' exists but is not a valid bare repo!" "$git_dir"
	fi

	git clone --bare https://codeberg.org/lucastavaresa/dotfiles etc/.dotfiles
	dotgit restore -WS .
	dotgit submodule update --init --recursive
	dotgit config --local --add remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*'
	dotgit fetch
	dotgit branch --set-upstream-to=origin/main main
fi

mkdir -p "$home/.mozilla/firefox/myprofile/chrome/"
cp etc/userChrome.css "$home/.mozilla/firefox/myprofile/chrome/"

mkdir -p "$home/.local/share/wget"
touch "$home/.local/share/wget/wgetrc"

doas nixos-rebuild switch -I nixos-config="$home/etc/nixos/configuration.nix" -I nixpkgs="$home/code/nixpkgs"
