# vim:fileencoding=utf-8:foldmethod=marker

[completion]
icon_file    = "🗒️"
icon_folder  = "📁"
icon_command = ">"

[which]
separator = " │ "

[icons]

"Desktop/"     = "🖥"
"Documents/"   = "📄"
"Downloads/"   = "⬇️ "
"Pictures/"    = "🖼"
"Music/"       = "🎵"
"Movies/"      = "🎬"
"Videos/"      = "🎥"
"Public/"      = "🫂"
"Library/"     = "📚"
"Development/" = "🖖"
".config/"     = "⚙"

# Git
".git/"          = "git"
".gitignore"     = "git"
".gitmodules"    = "git"
".gitattributes" = "git"

# Dotfiles
".bashrc"      = "$"
".bashprofile" = "$"
".profile"     = "$"

# Text
"*.txt" = "🗒️"
"*.md"  = "📘"
"*.rst" = "📘"
COPYING = "📃"
LICENSE = "📃"

# Archives
"*.zip"    = "📦"
"*.tar"    = "📦"
"*.gz"     = "📦"
"*.7z"     = "📦"
"*.bz2"    = "📦"
"*.xz"     = "📦"
"*.rar"    = "📦"
"*.tar.gz" = "📦"
"*.tgz"    = "📦"
"*.arc"    = "📦"
"*.arj"    = "📦"
"*.taz"    = "📦"
"*.lha"    = "📦"
"*.lz4"    = "📦"
"*.lzh"    = "📦"
"*.lzma"   = "📦"
"*.tlz"    = "📦"
"*.txz"    = "📦"
"*.tzo"    = "📦"
"*.t7z"    = "📦"
"*.z"      = "📦"
"*.dz"     = "📦"
"*.lrz"    = "📦"
"*.lz"     = "📦"
"*.lzo"    = "📦"
"*.zst"    = "📦"
"*.tzst"   = "📦"
"*.bz"     = "📦"
"*.tbz"    = "📦"
"*.tbz2"   = "📦"
"*.tz"     = "📦"
"*.deb"    = "📦"
"*.rpm"    = "📦"
"*.war"    = "📦"
"*.ear"    = "📦"
"*.sar"    = "📦"
"*.alz"    = "📦"
"*.ace"    = "📦"
"*.zoo"    = "📦"
"*.cpio"   = "📦"
"*.rz"     = "📦"
"*.cab"    = "📦"
"*.wim"    = "📦"
"*.swm"    = "📦"
"*.dwm"    = "📦"
"*.esd"    = "📦"

# Documents
"*.csv"  = "📰"
"*.doc"  = "📰"
"*.doct" = "📰"
"*.docx" = "📰"
"*.dot"  = "📰"
"*.odt"  = "📰"
"*.ods"  = "📰"
"*.ots"  = "📰"
"*.pdf"  = "📚"
"*.pom"  = "📚"
"*.pot"  = "📚"
"*.ppm"  = "📚"
"*.pps"  = "📚"
"*.ppt"  = "📚"
"*.potx" = "📚"
"*.ppmx" = "📚"
"*.ppsx" = "📚"
"*.pptx" = "📚"
"*.xlc"  = "📰"
"*.xlm"  = "📰"
"*.xml"  = "🌎"
"*.xls"  = "📰"
"*.xlt"  = "📰"
"*.xlsm" = "📰"
"*.xlsx" = "📰"
"*.xspf" = "📰"
"*.qt"   = "📰"
"*.dic"  = "📖"
"*.djvu" = "📚"
"*.epub" = "📚"
"*.tex"  = "📜"
"*.org"  = "🦄"
"*.log"  = "📙"
"*.bib"  = "🎓"

# Audio
"*.mp3"  = "🎵"
"*.flac" = "🎼"
"*.wav"  = "🎼"
"*.aac"  = "🎵"
"*.ogg"  = "🎵"
"*.m4a"  = "🎵"
"*.mp2"  = "🎵"
"*.opus" = "🎵"
"*.midi" = "🎵"
"*.mid"  = "🎵"
"*.au"   = "🎵"
"*.mka"  = "🎵"
"*.mpc"  = "🎵"
"*.ra"   = "🎵"
"*.oga"  = "🎵"
"*.spx"  = "🎵"

# Movies
"*.mp4"  = "🎥"
"*.mkv"  = "🎥"
"*.avi"  = "🎥"
"*.mov"  = "🎥"
"*.webm" = "🎥"
"*.asf"  = "🎥"
"*.rm"   = "🎥"
"*.rmvb" = "🎥"
"*.flc"  = "🎥"
"*.m2v"  = "🎥"
"*.mpeg" = "🎥"
"*.mpg"  = "🎥"
"*.wmv"  = "🎥"
"*.m4b"  = "🎥"
"*.flv"  = "🎥"
"*.ogm"  = "🎥"
"*.m4v"  = "🎥"
"*.mp4v" = "🎥"
"*.vob"  = "🎥"
"*.nuv"  = "🎥"
"*.fli"  = "🎥"
"*.ogv"  = "🎥"
"*.ogx"  = "🎥"

# Images
"*.jpg"   = "📸"
"*.jpe"   = "📸"
"*.jpeg"  = "📸"
"*.mjpg"  = "📸"
"*.mjpeg" = "📸"
"*.png"   = "🖼"
"*.gif"   = "🖼"
"*.webp"  = "🖼"
"*.avif"  = "📸"
"*.bmp"   = "🖼"
"*.ico"   = "🖼"
"*.svg"   = "🗺"
"*.svgz"  = "🗺"
"*.xcf"   = "🖌"
"*.HEIC"  = "📸"
"*.pgm"   = "🖼"
"*.pbm"   = "🖼"
"*.tga"   = "🖼"
"*.xbm"   = "🖼"
"*.xpm"   = "🖼"
"*.mng"   = "🗺"
"*.pcx"   = "🗺"
"*.tif"   = "🖼"
"*.tiff"  = "🖼"
"*.xwd"   = "🖼"
"*.yuv"   = "🖼"
"*.gl"    = "🖼"
"*.dl"    = "🖼"
"*.cgm"   = "🖼"
"*.emf"   = "🖼"

# Programming
"*.c"       = "C"
"*.cpp"     = "C++"
"*.h"       = "H"
"*.hh"      = "HH"
"*.hpp"     = "H++"
"*.rs"      = "🦀"
"*.go"      = "🐹"
"*.py"      = "🐍"
"*.r"       = "📊"
"*.R"       = "📊"
"*.rmd"     = "📊"
"*.m"       = "📊"
"*.js"      = "📜"
"*.ts"      = "📜"
"*.tsx"     = "📜"
"*.jsx"     = "📜"
"*.rb"      = "💎"
"*.php"     = "🐘"
"*.java"    = "♨"
"*.jar"     = "♨"
"*.cs"      = "C#"
"*.fs"      = "F#"
"*.el"      = "()"
"*.lisp"    = "()"
"*.coffee"  = "☕"
"*.d"       = "D"
"*.dart"    = "🎯"
"*.sh"      = "$"
"*.zsh"     = "$"
"*.bash"    = "$"
"*.fish"    = "🐟"
"*.cmd"     = "=>"
"*.ps1"     = "=>"
"*.lua"     = "🌙"
"*.nelua"   = "🌙"
"*.html"    = "🌎"
"*.css"     = "🎨"
"*.scss"    = "🎨"
"*.json"    = "{}"
"*.toml"    = "⚙ "
"*.yml"     = "⚙ "
"*.yaml"    = "⚙ "
"*.ini"     = "⚙ "
"*.cfg"     = "⚙ "
"*.conf"    = "⚙ "
"*.config"  = "⚙ "
"*.lock"    = "🔒"
"*.gpg"     = "🔒"
"*.kdbx"    = "🔒"
Dockerfile  = "🫙"
"*.hook"    = "🪝"
"*.ttf"     = ""
"*.otf"     = ""
"*.woff"    = ""
"*.woff2"   = ""
"*.iso"     = "📀"
"*.vdi"     = "📀"
"*.hdi"     = "📀"
"*.ged"     = "👪"
"*.part"    = "💔"
"*.torrent" = "🔽"
"*.mk"      = "🔨"
Makefile    = "🔨"
"*.rom"     = "🎮"
"*.nds"     = "🎮"
"*.n64"     = "🎮"
"*.z64"     = "🎮"
"*.v64"     = "🎮"
"*.gba"     = "🎮"
"*.nes"     = "🎮"
"*.gdi"     = "🎮"
"*.1"       = "ℹ"
"*.nfo"     = "ℹ"
"*.info"    = "ℹ"
Containerfile = "🫙"

# Misc
"*.desktop" = "🎯"
"*.so"      = "🎯"
"*.dll"     = "🎯"
"*.bin"     = "🎯"
"*.exe"     = "🎯"
"*.pkg"     = "🎯"

# Default
"*"  = "🗒️"
"*/" = "📁"
