# Coloca linhas entre os prompts
add_newline = true

# Reativa o relógio
[time]
disabled = false

# Troca o simbolo "❯" por ">"
[character]
# success_symbol = "[>](bold green)"

format = """$time
[>](bold green) """

# Desabilita a quebra de linha antes do ">"
[line_break]
disabled = true

[directory]
truncation_length = 4
