#!/bin/sh

# monitor
bspc monitor -d 1 2 3 4 5

# configurações
bspc config border_width            1
bspc config window_gap              0
bspc config top_padding             0
bspc config bottom_padding          0
bspc config left_padding            0
bspc config right_padding           0
bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config pointer_modifier        mod4
bspc config pointer_action1         move
bspc config click_to_focus          any
bspc config single_monocle          true

# cores
bspc config normal_border_color           "#000000"
bspc config active_border_color           "#ffffff"
bspc config focused_border_color          "#ffffff"
bspc config presel_feedback_color         "#333333"

# regras
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a mpv state=fullscreen
bspc rule -a guvcview state=floating rectangle=480x270+0+0 sticky=on layer=above
bspc rule -a Deadbeef state=floating rectangle=1200x600+0+0 sticky=on layer=above center=true
bspc rule -a ncmpcpp state=floating rectangle=1200x600+0+0 sticky=on layer=above center=true
bspc rule -a xev state=floating rectangle=480x270+0+0 sticky=on layer=above center=true
bspc rule -a Gcr-prompter state=floating rectangle=480x270+0+0 sticky=on layer=above center=true
bspc rule -a Transmission-gtk state=floating rectangle=1000x700+0+0 sticky=on layer=above center=true
bspc rule -a firefox:Places state=floating rectangle=480x270+0+0 sticky=off layer=above center=true
bspc rule -a confirm state=floating rectangle=480x270+0+0 sticky=on layer=above center=true
bspc rule -a file_progress state=floating rectangle=480x270+0+0 sticky=off layer=above center=true
bspc rule -a dialog state=floating rectangle=480x270+0+0 sticky=on layer=above center=true
bspc rule -a download state=floating rectangle=480x270+0+0 sticky=off layer=above
bspc rule -a MEGAsync:megasync state=floating rectangle=480x270+0+0 sticky=off layer=above center=true
bspc rule -a firefox:Devtools state=floating rectangle=800x350+0+0 sticky=on layer=above center=true
bspc rule -a Galculator:galculator state=floating rectangle=480x270+0+0 sticky=on layer=above center=true
bspc rule -a toolbar state=floating rectangle=480x270+0+0 sticky=off layer=above
bspc rule -a error state=floating rectangle=480x270+0+0 sticky=off layer=above center=true
bspc rule -a MPlayer state=floating rectangle=480x270+0+0 sticky=off layer=above center=true
bspc rule -a notification state=floating rectangle=480x270+0+0 sticky=off layer=above center=true
bspc rule -a pulsemixer state=floating rectangle=800x300+0+0 center=true
bspc rule -a VirtualBox Manager state=fullscreen
bspc rule -a VirtualBox Machine state=fullscreen
bspc rule -a :Zathura state=tiled
bspc rule -a st_download state=floating rectangle=1000x700+0+0 center=true

# polybar
if [ "$PC" = "linuxmint" ]; then
    polybar notebook &
    # espera a barra carregar e esconde a barra
    sleep 5 && polybar-msg cmd hide
elif [ "$PC" = "archlinux" ] || [ "$PC" = "manjaro" ]; then
    polybar pc &
    # espera a barra carregar e esconde a barra
    sleep 5 && polybar-msg cmd hide
fi

# teclas no notebook
if [ "$PC" = "linuxmint" ] || [ "$PC" = "manjaro" ]; then
    # alt + , = Escape
    xmodmap -e "keycode 59 = comma less comma less Escape"
    # alt + . = Tab
    xmodmap -e "keycode 60 = period greater period greater Tab"
    # alt + ; = "
    xmodmap -e "keycode 61 = semicolon colon semicolon colon quotedbl"
fi
