#!/usr/bin/env sh

CONFIG_FILE="$HOME/.config/qutebrowser/config.py"
TMP_FILE="$HOME/.cache/darkmode-add-tmpfile"

if grep -qxF "config.set('$2', True, '$1')" "$CONFIG_FILE"; then
	grep -vxF "config.set('$2', True, '$1')" "$CONFIG_FILE" >"$TMP_FILE"
	mv "$TMP_FILE" "$CONFIG_FILE"
else
	printf "config.set('$2', True, '%s')\n" "$1" >>"$CONFIG_FILE"
fi
