#!/usr/bin/env bash

script_path="/usr/local/bin"

prompt="-g 2 -p Menus:"

run_dmenu="$(find $script_path/* -maxdepth 1 -type f -executable \
          -exec grep -Iq . {} \; -print \
          | sed 's|^'$script_path/'||' \
          | sort \
          | dmenu $prompt )"

eval "$script_path/$run_dmenu"

exit 0
