#!/usr/bin/env bash

script_path="/usr/local/bin"

prompt="-g 2 -p Menus:"

run_dmenu="$(find /usr/local/bin/killmenu /usr/local/bin/dmenu_run_history /usr/local/bin/dmenu_sudo /usr/local/bin/clipmenu /usr/local/bin/dmenu_emoji -maxdepth 1 -type f -executable \
          -exec grep -Iq . {} \; -print \
          | sed 's|^'$script_path/'||' \
          | dmenu $prompt )"

eval "$script_path/$run_dmenu"

exit 0
