[colors]
black = #000000
gray = #555555
lightgrey = #777777
white = #ffffff
yellow = #ffff00
blue = #0000ff
lightblue = #0099ff
cyan = #00ffff
red = #ff0000
orange = #d65d0e
teal = #83a598
bg = #282828
fg = #d5c4a1

[bar/pc]
width = 100%
height = 20px
background = ${colors.bg}
foreground = ${colors.fg}
bottom = true
; Tag underline
line-size = 1px
; margem entre modulos
module-margin = 1
locale = pt_BR.UTF-8
; separator = "   "
; separator-foreground = ${colors.fg}
font-0 = "Terminus:pixelsize=14:antialias=true:autohint=true;1"
font-1 = "Iosevka Nerd Font Mono:size=20:antialias=true:autohint=true;3"
font-2 = "Noto Sans:size=14:antialias=true:hinting=true"
modules-left = xworkspaces
modules-center = musica pulseaudio
modules-right = filesystem battery backlight date
cursor-click = pointer
cursor-scroll = ns-resize
enable-ipc = true
tray-position = right
; controle do wm sobre a barra
; override-redirect = true
; wm-restack = generic
; wm-restack = bspwm
; wm-restack = i3

[module/backlight]
type = internal/backlight

[module/battery]
type = internal/battery
; This is useful in case the battery never reports 100% charge
full-at = 100
low-at = 10
; $ ls -1 /sys/class/power_supply/
battery = BAT0
adapter = ADP1
poll-interval = 5
time-format = %H:%M
format-charging = <animation-charging> <label-charging>
format-discharging = <ramp-capacity> <label-discharging>
format-full = <ramp-capacity> <label-full>
format-low = <label-low> <animation-low>
label-charging = Carregando %percentage%%
label-discharging = Descarregando %percentage%%
label-full = Carregado
label-low = Batteria baixa
ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
bar-capacity-width = 10
animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-framerate = 750
animation-discharging-0 = 
animation-discharging-1 = 
animation-discharging-2 = 
animation-discharging-3 = 
animation-discharging-4 = 
animation-discharging-framerate = 500
animation-low-0 = !
animation-low-1 =
animation-low-framerate = 200

[module/xworkspaces]
type = internal/xworkspaces
label-active = %icon%
label-active-background = ${colors.black}
label-active-foreground = ${colors.orange}
label-active-padding = 1
label-occupied = %icon%
label-occupied-padding = 1
label-occupied-foreground = ${colors.lightgrey}
label-urgent = %icon%
label-urgent-underline = ${colors.red}
label-urgent-padding = 1
label-empty = ""
label-empty-foreground = ${colors.bg}
label-empty-padding = 0
icon-0 = 1;
icon-1 = 2;
icon-2 = 3;
icon-3 = 4;
icon-default = ﱡ

[module/filesystem]
type = internal/fs
format-mounted = <label-mounted>
label-mounted = " %mountpoint% %free%"
label-mounted-foreground = ${colors.red}
mount-0 = /
mount-1 = /home
interval = 3600
fixed-values = true

[module/musica]
type = custom/script
exec = musica tocando
interval = 2
format = <label>
label = "%output%"
format-prefix = " "
label-foreground = ${colors.cyan}
format-prefix-foreground = ${colors.lightblue}

[module/pulseaudio]
type = internal/pulseaudio
format-volume = <ramp-volume><label-volume>
format-volume-foreground = ${colors.lightblue}
label-volume = %percentage:3:3%%
label-muted = "婢 mute"
label-volume-foreground = ${colors.cyan}
ramp-volume-0 = 
ramp-volume-1 = 墳
ramp-volume-2 = 

[module/date]
type = internal/date
; segundos
interval = 60
date = %a %d/%m/%Y - %H:%M
label = %date%
label-foreground = ${colors.fg}

[settings]
screenchange-reload = true
pseudo-transparency = true
