format = """$fill

$directory$username$cmd_duration$dotnet$package$jobs
$character"""

# Ativa o relógio
[time]
disabled = false

[line_break]
disabled = true

[directory]
style = "bold #0099FF"
truncation_length = 4
truncate_to_repo = false

[fill]
symbol = "."
style = "bold #ffffff"

