format = """$fill
$line_break
$username$directory$cmd_duration$dotnet$packege$jobs
$character"""

[line_break]
disabled = true

[directory]
style = "bold #0099FF"
truncation_length = 4
truncate_to_repo = false

[fill]
symbol = "🬋"
style = "bold #444444"

