#!/bin/sh
if [ "$OS" = "artixlinux" ] || [ "$OS" = "archlinux" ] || [ "$OS" = "manjaro" ]; then
    pacman -Qqem > "$HOME/extras/$HOSTNAME-aurpkgs.txt" && pacman -Qqen > "$HOME/extras/$HOSTNAME-nativepkgs.txt"
elif [ "$OS" = "voidlinux" ]; then
    xpkg -m > "$HOME/extras/$HOSTNAME-pkgs.txt"
fi
